// Static rental data for all rental categories
export interface StaticRental {
    id: string;
    providerId: string;
    providerName: string;
    name: string;
    description: string;
    price: number;
    priceUnit: string;
    category: string;
    rating: number;
    reviews: number;
    image: string;
    durationUnit: string;
    isAvailable: boolean;
    location: string;
    type: "rental";
}

const IMG = "https://images.unsplash.com/photo-";

export const staticRentals: StaticRental[] = [
    // ── CARS (15) ──
    { id: "r-c1", providerId: "rprov1", providerName: "AutoDrive Rentals", name: "Swift Dzire", description: "Compact sedan ideal for city travel", price: 1500, priceUnit: "day", category: "Cars", rating: 4.7, reviews: 234, image: IMG + "1549399542-7e3f8b79c341?w=400", durationUnit: "day", isAvailable: true, location: "Madurai", type: "rental" },
    { id: "r-c2", providerId: "rprov2", providerName: "CityWheels", name: "Hyundai i20", description: "Premium hatchback with great mileage", price: 1800, priceUnit: "day", category: "Cars", rating: 4.8, reviews: 189, image: IMG + "1552519507-88aa2dfa9fdb?w=400", durationUnit: "day", isAvailable: true, location: "Madurai", type: "rental" },
    { id: "r-c3", providerId: "rprov1", providerName: "AutoDrive Rentals", name: "Toyota Innova", description: "Spacious 7-seater for family trips", price: 3500, priceUnit: "day", category: "Cars", rating: 4.9, reviews: 312, image: IMG + "1544636331-e26879cd4d9b?w=400", durationUnit: "day", isAvailable: true, location: "Madurai", type: "rental" },
    { id: "r-c4", providerId: "rprov2", providerName: "CityWheels", name: "Maruti Alto", description: "Budget-friendly car for local errands", price: 800, priceUnit: "day", category: "Cars", rating: 4.3, reviews: 156, image: IMG + "1549399542-7e3f8b79c341?w=400", durationUnit: "day", isAvailable: true, location: "Madurai", type: "rental" },
    { id: "r-c5", providerId: "rprov1", providerName: "AutoDrive Rentals", name: "Honda City", description: "Premium sedan with smooth ride", price: 2500, priceUnit: "day", category: "Cars", rating: 4.8, reviews: 167, image: IMG + "1552519507-88aa2dfa9fdb?w=400", durationUnit: "day", isAvailable: true, location: "Madurai", type: "rental" },
    { id: "r-c6", providerId: "rprov2", providerName: "CityWheels", name: "Mahindra XUV700", description: "Powerful SUV for long drives", price: 4000, priceUnit: "day", category: "Cars", rating: 4.7, reviews: 98, image: IMG + "1544636331-e26879cd4d9b?w=400", durationUnit: "day", isAvailable: true, location: "Madurai", type: "rental" },
    { id: "r-c7", providerId: "rprov1", providerName: "AutoDrive Rentals", name: "Tata Nexon", description: "Compact SUV with 5-star safety", price: 2200, priceUnit: "day", category: "Cars", rating: 4.6, reviews: 134, image: IMG + "1549399542-7e3f8b79c341?w=400", durationUnit: "day", isAvailable: true, location: "Madurai", type: "rental" },
    { id: "r-c8", providerId: "rprov2", providerName: "CityWheels", name: "Kia Seltos", description: "Feature-rich mid-size SUV", price: 2800, priceUnit: "day", category: "Cars", rating: 4.5, reviews: 112, image: IMG + "1552519507-88aa2dfa9fdb?w=400", durationUnit: "day", isAvailable: true, location: "Madurai", type: "rental" },
    { id: "r-c9", providerId: "rprov1", providerName: "AutoDrive Rentals", name: "Ertiga 7-Seater", description: "MPV perfect for group outings", price: 2500, priceUnit: "day", category: "Cars", rating: 4.4, reviews: 87, image: IMG + "1544636331-e26879cd4d9b?w=400", durationUnit: "day", isAvailable: true, location: "Madurai", type: "rental" },
    { id: "r-c10", providerId: "rprov2", providerName: "CityWheels", name: "Wagon R", description: "Tall-boy design with spacious cabin", price: 1000, priceUnit: "day", category: "Cars", rating: 4.3, reviews: 198, image: IMG + "1549399542-7e3f8b79c341?w=400", durationUnit: "day", isAvailable: true, location: "Madurai", type: "rental" },
    { id: "r-c11", providerId: "rprov1", providerName: "AutoDrive Rentals", name: "Fortuner 4x4", description: "Rugged off-road capable SUV", price: 6000, priceUnit: "day", category: "Cars", rating: 4.9, reviews: 56, image: IMG + "1552519507-88aa2dfa9fdb?w=400", durationUnit: "day", isAvailable: true, location: "Madurai", type: "rental" },
    { id: "r-c12", providerId: "rprov2", providerName: "CityWheels", name: "Creta Diesel", description: "Popular SUV with turbo diesel engine", price: 2600, priceUnit: "day", category: "Cars", rating: 4.6, reviews: 145, image: IMG + "1544636331-e26879cd4d9b?w=400", durationUnit: "day", isAvailable: true, location: "Madurai", type: "rental" },
    { id: "r-c13", providerId: "rprov1", providerName: "AutoDrive Rentals", name: "Baleno Automatic", description: "Easy-drive automatic transmission hatch", price: 1600, priceUnit: "day", category: "Cars", rating: 4.5, reviews: 78, image: IMG + "1549399542-7e3f8b79c341?w=400", durationUnit: "day", isAvailable: true, location: "Madurai", type: "rental" },
    { id: "r-c14", providerId: "rprov2", providerName: "CityWheels", name: "Thar 4x4", description: "Adventure-ready convertible SUV", price: 4500, priceUnit: "day", category: "Cars", rating: 4.8, reviews: 67, image: IMG + "1552519507-88aa2dfa9fdb?w=400", durationUnit: "day", isAvailable: true, location: "Madurai", type: "rental" },
    { id: "r-c15", providerId: "rprov1", providerName: "AutoDrive Rentals", name: "Tempo Traveller", description: "12-seater van for group travel", price: 5000, priceUnit: "day", category: "Cars", rating: 4.7, reviews: 89, image: IMG + "1544636331-e26879cd4d9b?w=400", durationUnit: "day", isAvailable: true, location: "Madurai", type: "rental" },

    // ── BIKES (15) ──
    { id: "r-b1", providerId: "rprov3", providerName: "RideOn Bikes", name: "Royal Enfield Classic", description: "Iconic 350cc cruiser bike", price: 800, priceUnit: "day", category: "Bikes", rating: 4.8, reviews: 267, image: IMG + "1558981806-ec527fa84c39?w=400", durationUnit: "day", isAvailable: true, location: "Madurai", type: "rental" },
    { id: "r-b2", providerId: "rprov4", providerName: "TwoWheeler Hub", name: "Honda Activa", description: "Fuel-efficient automatic scooter", price: 350, priceUnit: "day", category: "Bikes", rating: 4.6, reviews: 345, image: IMG + "1558981806-ec527fa84c39?w=400", durationUnit: "day", isAvailable: true, location: "Madurai", type: "rental" },
    { id: "r-b3", providerId: "rprov3", providerName: "RideOn Bikes", name: "KTM Duke 200", description: "Sporty street performance bike", price: 1200, priceUnit: "day", category: "Bikes", rating: 4.7, reviews: 178, image: IMG + "1558981806-ec527fa84c39?w=400", durationUnit: "day", isAvailable: true, location: "Madurai", type: "rental" },
    { id: "r-b4", providerId: "rprov4", providerName: "TwoWheeler Hub", name: "TVS Jupiter", description: "Comfortable scooter for daily commute", price: 300, priceUnit: "day", category: "Bikes", rating: 4.4, reviews: 234, image: IMG + "1558981806-ec527fa84c39?w=400", durationUnit: "day", isAvailable: true, location: "Madurai", type: "rental" },
    { id: "r-b5", providerId: "rprov3", providerName: "RideOn Bikes", name: "Yamaha R15", description: "Sport bike for enthusiasts", price: 1000, priceUnit: "day", category: "Bikes", rating: 4.8, reviews: 145, image: IMG + "1558981806-ec527fa84c39?w=400", durationUnit: "day", isAvailable: true, location: "Madurai", type: "rental" },
    { id: "r-b6", providerId: "rprov4", providerName: "TwoWheeler Hub", name: "Honda SP 125", description: "Fuel-efficient commuter bike", price: 400, priceUnit: "day", category: "Bikes", rating: 4.5, reviews: 198, image: IMG + "1558981806-ec527fa84c39?w=400", durationUnit: "day", isAvailable: true, location: "Madurai", type: "rental" },
    { id: "r-b7", providerId: "rprov3", providerName: "RideOn Bikes", name: "Bajaj Pulsar NS200", description: "Powerful naked sport bike", price: 700, priceUnit: "day", category: "Bikes", rating: 4.6, reviews: 123, image: IMG + "1558981806-ec527fa84c39?w=400", durationUnit: "day", isAvailable: true, location: "Madurai", type: "rental" },
    { id: "r-b8", providerId: "rprov4", providerName: "TwoWheeler Hub", name: "TVS NTorq", description: "Sporty scooter with smart features", price: 400, priceUnit: "day", category: "Bikes", rating: 4.3, reviews: 167, image: IMG + "1558981806-ec527fa84c39?w=400", durationUnit: "day", isAvailable: true, location: "Madurai", type: "rental" },
    { id: "r-b9", providerId: "rprov3", providerName: "RideOn Bikes", name: "RE Himalayan", description: "Adventure tourer for road trips", price: 1500, priceUnit: "day", category: "Bikes", rating: 4.9, reviews: 89, image: IMG + "1558981806-ec527fa84c39?w=400", durationUnit: "day", isAvailable: true, location: "Madurai", type: "rental" },
    { id: "r-b10", providerId: "rprov4", providerName: "TwoWheeler Hub", name: "Apache RTR 160", description: "Street racing inspired commuter", price: 500, priceUnit: "day", category: "Bikes", rating: 4.5, reviews: 112, image: IMG + "1558981806-ec527fa84c39?w=400", durationUnit: "day", isAvailable: true, location: "Madurai", type: "rental" },
    { id: "r-b11", providerId: "rprov3", providerName: "RideOn Bikes", name: "Dominar 400", description: "Long-distance touring bike", price: 900, priceUnit: "day", category: "Bikes", rating: 4.7, reviews: 67, image: IMG + "1558981806-ec527fa84c39?w=400", durationUnit: "day", isAvailable: true, location: "Madurai", type: "rental" },
    { id: "r-b12", providerId: "rprov4", providerName: "TwoWheeler Hub", name: "Vespa SXL", description: "Italian-style premium scooter", price: 600, priceUnit: "day", category: "Bikes", rating: 4.4, reviews: 45, image: IMG + "1558981806-ec527fa84c39?w=400", durationUnit: "day", isAvailable: true, location: "Madurai", type: "rental" },
    { id: "r-b13", providerId: "rprov3", providerName: "RideOn Bikes", name: "Hero Splendor", description: "India's most reliable commuter", price: 250, priceUnit: "day", category: "Bikes", rating: 4.2, reviews: 289, image: IMG + "1558981806-ec527fa84c39?w=400", durationUnit: "day", isAvailable: true, location: "Madurai", type: "rental" },
    { id: "r-b14", providerId: "rprov4", providerName: "TwoWheeler Hub", name: "Suzuki Access", description: "Light and nimble city scooter", price: 350, priceUnit: "day", category: "Bikes", rating: 4.5, reviews: 156, image: IMG + "1558981806-ec527fa84c39?w=400", durationUnit: "day", isAvailable: true, location: "Madurai", type: "rental" },
    { id: "r-b15", providerId: "rprov3", providerName: "RideOn Bikes", name: "Jawa Perak", description: "Bobber-style cruiser motorcycle", price: 1100, priceUnit: "day", category: "Bikes", rating: 4.6, reviews: 34, image: IMG + "1558981806-ec527fa84c39?w=400", durationUnit: "day", isAvailable: true, location: "Madurai", type: "rental" },

    // ── TOOLS (15) ──
    { id: "r-t1", providerId: "rprov5", providerName: "ToolBox Rentals", name: "Power Drill Set", description: "Bosch cordless drill with bit set", price: 200, priceUnit: "day", category: "Tools", rating: 4.7, reviews: 156, image: IMG + "1504148455328-c376907d081c?w=400", durationUnit: "day", isAvailable: true, location: "Madurai", type: "rental" },
    { id: "r-t2", providerId: "rprov6", providerName: "BuildRight Tools", name: "Angle Grinder", description: "Heavy-duty 4-inch angle grinder", price: 250, priceUnit: "day", category: "Tools", rating: 4.5, reviews: 98, image: IMG + "1504148455328-c376907d081c?w=400", durationUnit: "day", isAvailable: true, location: "Madurai", type: "rental" },
    { id: "r-t3", providerId: "rprov5", providerName: "ToolBox Rentals", name: "Pressure Washer", description: "2000 PSI electric pressure washer", price: 500, priceUnit: "day", category: "Tools", rating: 4.8, reviews: 134, image: IMG + "1504148455328-c376907d081c?w=400", durationUnit: "day", isAvailable: true, location: "Madurai", type: "rental" },
    { id: "r-t4", providerId: "rprov6", providerName: "BuildRight Tools", name: "Welding Machine", description: "Arc welding machine with rods", price: 400, priceUnit: "day", category: "Tools", rating: 4.6, reviews: 67, image: IMG + "1504148455328-c376907d081c?w=400", durationUnit: "day", isAvailable: true, location: "Madurai", type: "rental" },
    { id: "r-t5", providerId: "rprov5", providerName: "ToolBox Rentals", name: "Tile Cutter", description: "Manual and electric tile cutting machine", price: 300, priceUnit: "day", category: "Tools", rating: 4.4, reviews: 45, image: IMG + "1504148455328-c376907d081c?w=400", durationUnit: "day", isAvailable: true, location: "Madurai", type: "rental" },
    { id: "r-t6", providerId: "rprov6", providerName: "BuildRight Tools", name: "Concrete Mixer", description: "Portable concrete mixing drum", price: 800, priceUnit: "day", category: "Tools", rating: 4.7, reviews: 34, image: IMG + "1504148455328-c376907d081c?w=400", durationUnit: "day", isAvailable: true, location: "Madurai", type: "rental" },
    { id: "r-t7", providerId: "rprov5", providerName: "ToolBox Rentals", name: "Scaffolding Set", description: "Aluminum scaffolding tower 4m height", price: 600, priceUnit: "day", category: "Tools", rating: 4.5, reviews: 28, image: IMG + "1504148455328-c376907d081c?w=400", durationUnit: "day", isAvailable: true, location: "Madurai", type: "rental" },
    { id: "r-t8", providerId: "rprov6", providerName: "BuildRight Tools", name: "Generator 3KVA", description: "Portable petrol generator for power backup", price: 700, priceUnit: "day", category: "Tools", rating: 4.8, reviews: 56, image: IMG + "1504148455328-c376907d081c?w=400", durationUnit: "day", isAvailable: true, location: "Madurai", type: "rental" },
    { id: "r-t9", providerId: "rprov5", providerName: "ToolBox Rentals", name: "Ladder 20ft", description: "Aluminum extension ladder", price: 150, priceUnit: "day", category: "Tools", rating: 4.3, reviews: 89, image: IMG + "1504148455328-c376907d081c?w=400", durationUnit: "day", isAvailable: true, location: "Madurai", type: "rental" },
    { id: "r-t10", providerId: "rprov6", providerName: "BuildRight Tools", name: "Chainsaw", description: "Petrol chainsaw for tree cutting", price: 500, priceUnit: "day", category: "Tools", rating: 4.6, reviews: 23, image: IMG + "1504148455328-c376907d081c?w=400", durationUnit: "day", isAvailable: true, location: "Madurai", type: "rental" },
    { id: "r-t11", providerId: "rprov5", providerName: "ToolBox Rentals", name: "Paint Sprayer", description: "Airless paint spray gun", price: 350, priceUnit: "day", category: "Tools", rating: 4.4, reviews: 45, image: IMG + "1504148455328-c376907d081c?w=400", durationUnit: "day", isAvailable: true, location: "Madurai", type: "rental" },
    { id: "r-t12", providerId: "rprov6", providerName: "BuildRight Tools", name: "Demolition Hammer", description: "Heavy-duty electric breaker", price: 600, priceUnit: "day", category: "Tools", rating: 4.7, reviews: 12, image: IMG + "1504148455328-c376907d081c?w=400", durationUnit: "day", isAvailable: true, location: "Madurai", type: "rental" },
    { id: "r-t13", providerId: "rprov5", providerName: "ToolBox Rentals", name: "Measuring Kit", description: "Laser level, tape, and measuring tools", price: 100, priceUnit: "day", category: "Tools", rating: 4.5, reviews: 78, image: IMG + "1504148455328-c376907d081c?w=400", durationUnit: "day", isAvailable: true, location: "Madurai", type: "rental" },
    { id: "r-t14", providerId: "rprov6", providerName: "BuildRight Tools", name: "Compressor 5HP", description: "Air compressor for pneumatic tools", price: 450, priceUnit: "day", category: "Tools", rating: 4.6, reviews: 34, image: IMG + "1504148455328-c376907d081c?w=400", durationUnit: "day", isAvailable: true, location: "Madurai", type: "rental" },
    { id: "r-t15", providerId: "rprov5", providerName: "ToolBox Rentals", name: "Sander Machine", description: "Orbital sander for wood and wall finishing", price: 200, priceUnit: "day", category: "Tools", rating: 4.3, reviews: 56, image: IMG + "1504148455328-c376907d081c?w=400", durationUnit: "day", isAvailable: true, location: "Madurai", type: "rental" },

    // ── AV/EVENTS (15) ──
    { id: "r-av1", providerId: "rprov7", providerName: "EventTech Rentals", name: "DJ Sound System", description: "Professional 2000W DJ speakers with mixer", price: 3000, priceUnit: "event", category: "AV/Events", rating: 4.8, reviews: 189, image: IMG + "1470229722913-7c0e2dbbafd3?w=400", durationUnit: "day", isAvailable: true, location: "Madurai", type: "rental" },
    { id: "r-av2", providerId: "rprov8", providerName: "StageCraft Pro", name: "LED Projector 5000L", description: "HD projector for presentations and movies", price: 1500, priceUnit: "day", category: "AV/Events", rating: 4.7, reviews: 134, image: IMG + "1470229722913-7c0e2dbbafd3?w=400", durationUnit: "day", isAvailable: true, location: "Madurai", type: "rental" },
    { id: "r-av3", providerId: "rprov7", providerName: "EventTech Rentals", name: "Stage Lighting Kit", description: "Par lights, moving heads, and controller", price: 5000, priceUnit: "event", category: "AV/Events", rating: 4.9, reviews: 87, image: IMG + "1470229722913-7c0e2dbbafd3?w=400", durationUnit: "day", isAvailable: true, location: "Madurai", type: "rental" },
    { id: "r-av4", providerId: "rprov8", providerName: "StageCraft Pro", name: "Wireless Mic Set", description: "2-channel wireless microphone system", price: 800, priceUnit: "day", category: "AV/Events", rating: 4.5, reviews: 198, image: IMG + "1470229722913-7c0e2dbbafd3?w=400", durationUnit: "day", isAvailable: true, location: "Madurai", type: "rental" },
    { id: "r-av5", providerId: "rprov7", providerName: "EventTech Rentals", name: "PA System 500W", description: "Public address system for events", price: 2000, priceUnit: "day", category: "AV/Events", rating: 4.6, reviews: 67, image: IMG + "1470229722913-7c0e2dbbafd3?w=400", durationUnit: "day", isAvailable: true, location: "Madurai", type: "rental" },
    { id: "r-av6", providerId: "rprov8", providerName: "StageCraft Pro", name: "LED Screen 55in", description: "Large LED display for events and exhibitions", price: 2500, priceUnit: "day", category: "AV/Events", rating: 4.7, reviews: 45, image: IMG + "1470229722913-7c0e2dbbafd3?w=400", durationUnit: "day", isAvailable: true, location: "Madurai", type: "rental" },
    { id: "r-av7", providerId: "rprov7", providerName: "EventTech Rentals", name: "Karaoke Machine", description: "Karaoke system with songbook and mics", price: 1000, priceUnit: "day", category: "AV/Events", rating: 4.4, reviews: 112, image: IMG + "1470229722913-7c0e2dbbafd3?w=400", durationUnit: "day", isAvailable: true, location: "Madurai", type: "rental" },
    { id: "r-av8", providerId: "rprov8", providerName: "StageCraft Pro", name: "Fog Machine", description: "Theatrical fog/haze effect machine", price: 500, priceUnit: "day", category: "AV/Events", rating: 4.3, reviews: 56, image: IMG + "1470229722913-7c0e2dbbafd3?w=400", durationUnit: "day", isAvailable: true, location: "Madurai", type: "rental" },
    { id: "r-av9", providerId: "rprov7", providerName: "EventTech Rentals", name: "Photo Booth Setup", description: "Selfie booth with props and instant printing", price: 4000, priceUnit: "event", category: "AV/Events", rating: 4.8, reviews: 78, image: IMG + "1470229722913-7c0e2dbbafd3?w=400", durationUnit: "day", isAvailable: true, location: "Madurai", type: "rental" },
    { id: "r-av10", providerId: "rprov8", providerName: "StageCraft Pro", name: "Portable Stage", description: "Modular stage platform 8x8ft", price: 3000, priceUnit: "day", category: "AV/Events", rating: 4.6, reviews: 23, image: IMG + "1470229722913-7c0e2dbbafd3?w=400", durationUnit: "day", isAvailable: true, location: "Madurai", type: "rental" },
    { id: "r-av11", providerId: "rprov7", providerName: "EventTech Rentals", name: "Tent/Canopy 20x20", description: "Waterproof canopy tent for outdoor events", price: 2000, priceUnit: "day", category: "AV/Events", rating: 4.5, reviews: 89, image: IMG + "1470229722913-7c0e2dbbafd3?w=400", durationUnit: "day", isAvailable: true, location: "Madurai", type: "rental" },
    { id: "r-av12", providerId: "rprov8", providerName: "StageCraft Pro", name: "Tables & Chairs Set", description: "50 chairs + 5 round tables for events", price: 1500, priceUnit: "event", category: "AV/Events", rating: 4.4, reviews: 134, image: IMG + "1470229722913-7c0e2dbbafd3?w=400", durationUnit: "day", isAvailable: true, location: "Madurai", type: "rental" },
    { id: "r-av13", providerId: "rprov7", providerName: "EventTech Rentals", name: "Backdrop Stand", description: "Adjustable backdrop frame with drapes", price: 800, priceUnit: "day", category: "AV/Events", rating: 4.3, reviews: 45, image: IMG + "1470229722913-7c0e2dbbafd3?w=400", durationUnit: "day", isAvailable: true, location: "Madurai", type: "rental" },
    { id: "r-av14", providerId: "rprov8", providerName: "StageCraft Pro", name: "LED Dance Floor", description: "Illuminated dance floor panels", price: 6000, priceUnit: "event", category: "AV/Events", rating: 4.9, reviews: 12, image: IMG + "1470229722913-7c0e2dbbafd3?w=400", durationUnit: "day", isAvailable: true, location: "Madurai", type: "rental" },
    { id: "r-av15", providerId: "rprov7", providerName: "EventTech Rentals", name: "Generator 10KVA", description: "Silent generator for event power backup", price: 3500, priceUnit: "day", category: "AV/Events", rating: 4.7, reviews: 34, image: IMG + "1470229722913-7c0e2dbbafd3?w=400", durationUnit: "day", isAvailable: true, location: "Madurai", type: "rental" },

    // ── CAMPING (15) ──
    { id: "r-cm1", providerId: "rprov9", providerName: "WildTrail Gear", name: "4-Person Tent", description: "Waterproof dome tent for 4 people", price: 500, priceUnit: "day", category: "Camping", rating: 4.8, reviews: 167, image: IMG + "1504280390367-361c6d9f38f4?w=400", durationUnit: "day", isAvailable: true, location: "Madurai", type: "rental" },
    { id: "r-cm2", providerId: "rprov10", providerName: "NatureCamp Rentals", name: "Sleeping Bag", description: "Zero-degree rated sleeping bag", price: 150, priceUnit: "day", category: "Camping", rating: 4.6, reviews: 234, image: IMG + "1504280390367-361c6d9f38f4?w=400", durationUnit: "day", isAvailable: true, location: "Madurai", type: "rental" },
    { id: "r-cm3", providerId: "rprov9", providerName: "WildTrail Gear", name: "Camping Stove", description: "Portable gas stove with windscreen", price: 200, priceUnit: "day", category: "Camping", rating: 4.5, reviews: 123, image: IMG + "1504280390367-361c6d9f38f4?w=400", durationUnit: "day", isAvailable: true, location: "Madurai", type: "rental" },
    { id: "r-cm4", providerId: "rprov10", providerName: "NatureCamp Rentals", name: "Trekking Backpack 60L", description: "Ergonomic hiking backpack with rain cover", price: 250, priceUnit: "day", category: "Camping", rating: 4.7, reviews: 98, image: IMG + "1504280390367-361c6d9f38f4?w=400", durationUnit: "day", isAvailable: true, location: "Madurai", type: "rental" },
    { id: "r-cm5", providerId: "rprov9", providerName: "WildTrail Gear", name: "Camping Chair Set", description: "Foldable camping chairs (set of 4)", price: 300, priceUnit: "day", category: "Camping", rating: 4.4, reviews: 78, image: IMG + "1504280390367-361c6d9f38f4?w=400", durationUnit: "day", isAvailable: true, location: "Madurai", type: "rental" },
    { id: "r-cm6", providerId: "rprov10", providerName: "NatureCamp Rentals", name: "Headlamp + Lantern", description: "LED headlamp and solar lantern combo", price: 100, priceUnit: "day", category: "Camping", rating: 4.3, reviews: 145, image: IMG + "1504280390367-361c6d9f38f4?w=400", durationUnit: "day", isAvailable: true, location: "Madurai", type: "rental" },
    { id: "r-cm7", providerId: "rprov9", providerName: "WildTrail Gear", name: "Cookware Set", description: "Lightweight camping pots, pans, and utensils", price: 180, priceUnit: "day", category: "Camping", rating: 4.6, reviews: 56, image: IMG + "1504280390367-361c6d9f38f4?w=400", durationUnit: "day", isAvailable: true, location: "Madurai", type: "rental" },
    { id: "r-cm8", providerId: "rprov10", providerName: "NatureCamp Rentals", name: "Hammock", description: "Double hammock with tree straps", price: 120, priceUnit: "day", category: "Camping", rating: 4.5, reviews: 89, image: IMG + "1504280390367-361c6d9f38f4?w=400", durationUnit: "day", isAvailable: true, location: "Madurai", type: "rental" },
    { id: "r-cm9", providerId: "rprov9", providerName: "WildTrail Gear", name: "Trekking Poles", description: "Adjustable carbon fiber trekking poles", price: 100, priceUnit: "day", category: "Camping", rating: 4.4, reviews: 67, image: IMG + "1504280390367-361c6d9f38f4?w=400", durationUnit: "day", isAvailable: true, location: "Madurai", type: "rental" },
    { id: "r-cm10", providerId: "rprov10", providerName: "NatureCamp Rentals", name: "Kayak Single", description: "Inflatable single-person kayak with paddle", price: 800, priceUnit: "day", category: "Camping", rating: 4.8, reviews: 34, image: IMG + "1504280390367-361c6d9f38f4?w=400", durationUnit: "day", isAvailable: true, location: "Madurai", type: "rental" },
    { id: "r-cm11", providerId: "rprov9", providerName: "WildTrail Gear", name: "Binoculars", description: "10x42 waterproof binoculars for birding", price: 150, priceUnit: "day", category: "Camping", rating: 4.7, reviews: 45, image: IMG + "1504280390367-361c6d9f38f4?w=400", durationUnit: "day", isAvailable: true, location: "Madurai", type: "rental" },
    { id: "r-cm12", providerId: "rprov10", providerName: "NatureCamp Rentals", name: "Portable Shower", description: "Solar-heated camping shower bag", price: 80, priceUnit: "day", category: "Camping", rating: 4.2, reviews: 23, image: IMG + "1504280390367-361c6d9f38f4?w=400", durationUnit: "day", isAvailable: true, location: "Madurai", type: "rental" },
    { id: "r-cm13", providerId: "rprov9", providerName: "WildTrail Gear", name: "Cooler Box 50L", description: "Insulated ice chest for food storage", price: 200, priceUnit: "day", category: "Camping", rating: 4.5, reviews: 56, image: IMG + "1504280390367-361c6d9f38f4?w=400", durationUnit: "day", isAvailable: true, location: "Madurai", type: "rental" },
    { id: "r-cm14", providerId: "rprov10", providerName: "NatureCamp Rentals", name: "Camp Table", description: "Foldable aluminum camping table", price: 150, priceUnit: "day", category: "Camping", rating: 4.4, reviews: 34, image: IMG + "1504280390367-361c6d9f38f4?w=400", durationUnit: "day", isAvailable: true, location: "Madurai", type: "rental" },
    { id: "r-cm15", providerId: "rprov9", providerName: "WildTrail Gear", name: "First Aid Kit", description: "Comprehensive outdoor first aid kit", price: 50, priceUnit: "day", category: "Camping", rating: 4.9, reviews: 178, image: IMG + "1504280390367-361c6d9f38f4?w=400", durationUnit: "day", isAvailable: true, location: "Madurai", type: "rental" },

    // ── CAMERAS (15) ──
    { id: "r-ca1", providerId: "rprov11", providerName: "LensPro Rentals", name: "Canon EOS R6", description: "Full-frame mirrorless with 24-105mm lens", price: 2500, priceUnit: "day", category: "Cameras", rating: 4.9, reviews: 178, image: IMG + "1516035069371-29a1b244cc32?w=400", durationUnit: "day", isAvailable: true, location: "Madurai", type: "rental" },
    { id: "r-ca2", providerId: "rprov12", providerName: "ShutterBox", name: "Sony A7 III", description: "Professional mirrorless body with 28-70mm", price: 2800, priceUnit: "day", category: "Cameras", rating: 4.8, reviews: 156, image: IMG + "1516035069371-29a1b244cc32?w=400", durationUnit: "day", isAvailable: true, location: "Madurai", type: "rental" },
    { id: "r-ca3", providerId: "rprov11", providerName: "LensPro Rentals", name: "GoPro Hero 12", description: "Action camera for adventure shooting", price: 800, priceUnit: "day", category: "Cameras", rating: 4.7, reviews: 234, image: IMG + "1516035069371-29a1b244cc32?w=400", durationUnit: "day", isAvailable: true, location: "Madurai", type: "rental" },
    { id: "r-ca4", providerId: "rprov12", providerName: "ShutterBox", name: "DJI Mavic 3", description: "Professional drone with 4K camera", price: 3500, priceUnit: "day", category: "Cameras", rating: 4.9, reviews: 89, image: IMG + "1516035069371-29a1b244cc32?w=400", durationUnit: "day", isAvailable: true, location: "Madurai", type: "rental" },
    { id: "r-ca5", providerId: "rprov11", providerName: "LensPro Rentals", name: "Canon 70-200mm f/2.8", description: "Telephoto zoom lens for portraits and events", price: 1200, priceUnit: "day", category: "Cameras", rating: 4.8, reviews: 112, image: IMG + "1516035069371-29a1b244cc32?w=400", durationUnit: "day", isAvailable: true, location: "Madurai", type: "rental" },
    { id: "r-ca6", providerId: "rprov12", providerName: "ShutterBox", name: "DJI Ronin RS3", description: "3-axis camera gimbal stabilizer", price: 1500, priceUnit: "day", category: "Cameras", rating: 4.6, reviews: 67, image: IMG + "1516035069371-29a1b244cc32?w=400", durationUnit: "day", isAvailable: true, location: "Madurai", type: "rental" },
    { id: "r-ca7", providerId: "rprov11", providerName: "LensPro Rentals", name: "Studio Light Kit", description: "3-point softbox lighting setup", price: 1000, priceUnit: "day", category: "Cameras", rating: 4.5, reviews: 98, image: IMG + "1516035069371-29a1b244cc32?w=400", durationUnit: "day", isAvailable: true, location: "Madurai", type: "rental" },
    { id: "r-ca8", providerId: "rprov12", providerName: "ShutterBox", name: "Green Screen Kit", description: "Collapsible green screen with stand", price: 500, priceUnit: "day", category: "Cameras", rating: 4.4, reviews: 45, image: IMG + "1516035069371-29a1b244cc32?w=400", durationUnit: "day", isAvailable: true, location: "Madurai", type: "rental" },
    { id: "r-ca9", providerId: "rprov11", providerName: "LensPro Rentals", name: "Nikon Z6 II", description: "Versatile mirrorless with 24-70mm", price: 2200, priceUnit: "day", category: "Cameras", rating: 4.7, reviews: 78, image: IMG + "1516035069371-29a1b244cc32?w=400", durationUnit: "day", isAvailable: true, location: "Madurai", type: "rental" },
    { id: "r-ca10", providerId: "rprov12", providerName: "ShutterBox", name: "Tripod Professional", description: "Heavy-duty carbon fiber tripod with head", price: 300, priceUnit: "day", category: "Cameras", rating: 4.3, reviews: 134, image: IMG + "1516035069371-29a1b244cc32?w=400", durationUnit: "day", isAvailable: true, location: "Madurai", type: "rental" },
    { id: "r-ca11", providerId: "rprov11", providerName: "LensPro Rentals", name: "Sony 24-70mm GM", description: "Premium wide-angle zoom lens", price: 1500, priceUnit: "day", category: "Cameras", rating: 4.8, reviews: 56, image: IMG + "1516035069371-29a1b244cc32?w=400", durationUnit: "day", isAvailable: true, location: "Madurai", type: "rental" },
    { id: "r-ca12", providerId: "rprov12", providerName: "ShutterBox", name: "Video Camera 4K", description: "Professional camcorder for events", price: 2000, priceUnit: "day", category: "Cameras", rating: 4.6, reviews: 45, image: IMG + "1516035069371-29a1b244cc32?w=400", durationUnit: "day", isAvailable: true, location: "Madurai", type: "rental" },
    { id: "r-ca13", providerId: "rprov11", providerName: "LensPro Rentals", name: "Flash Speedlite", description: "External flash with diffuser", price: 400, priceUnit: "day", category: "Cameras", rating: 4.5, reviews: 89, image: IMG + "1516035069371-29a1b244cc32?w=400", durationUnit: "day", isAvailable: true, location: "Madurai", type: "rental" },
    { id: "r-ca14", providerId: "rprov12", providerName: "ShutterBox", name: "Macro Lens 100mm", description: "Close-up macro photography lens", price: 800, priceUnit: "day", category: "Cameras", rating: 4.7, reviews: 34, image: IMG + "1516035069371-29a1b244cc32?w=400", durationUnit: "day", isAvailable: true, location: "Madurai", type: "rental" },
    { id: "r-ca15", providerId: "rprov11", providerName: "LensPro Rentals", name: "Camera Bag Pro", description: "Large padded camera backpack", price: 150, priceUnit: "day", category: "Cameras", rating: 4.4, reviews: 67, image: IMG + "1516035069371-29a1b244cc32?w=400", durationUnit: "day", isAvailable: true, location: "Madurai", type: "rental" },
];
