// Static service data for all service categories
export interface StaticService {
    id: string;
    providerId: string;
    providerName: string;
    title: string;
    category: string;
    price: number;
    priceUnit: string;
    description: string;
    location: string;
    image: string;
    rating: number;
    reviews: number;
    availability: string;
    type: "service";
}

const IMG = "https://images.unsplash.com/photo-";

export const staticServices: StaticService[] = [
    // ── PLUMBING (15) ──
    { id: "s-p1", providerId: "prov1", providerName: "Kumar Plumbing Works", title: "Pipe Leak Repair", category: "Plumbing", price: 350, priceUnit: "visit", description: "Fix leaking pipes quickly with lasting results", location: "Madurai", image: IMG + "1585704032915-9e4a413f5a45?w=400", rating: 4.8, reviews: 124, availability: "Available Now", type: "service" },
    { id: "s-p2", providerId: "prov2", providerName: "AquaFix Solutions", title: "Drain Cleaning", category: "Plumbing", price: 500, priceUnit: "visit", description: "Complete drain unclogging and cleaning service", location: "Madurai", image: IMG + "1607472586893-edb57bdc0e39?w=400", rating: 4.6, reviews: 89, availability: "Available Now", type: "service" },
    { id: "s-p3", providerId: "prov3", providerName: "PipeMasters", title: "Bathroom Fitting", category: "Plumbing", price: 1200, priceUnit: "job", description: "Full bathroom tap and fixture installation", location: "Madurai", image: IMG + "1584622650111-993a426bc7e4?w=400", rating: 4.9, reviews: 201, availability: "Available Now", type: "service" },
    { id: "s-p4", providerId: "prov4", providerName: "Raj Water Works", title: "Water Tank Cleaning", category: "Plumbing", price: 800, priceUnit: "tank", description: "Thorough overhead and underground tank cleaning", location: "Madurai", image: IMG + "1504328345606-18bbc8c9d7d1?w=400", rating: 4.5, reviews: 67, availability: "Available Now", type: "service" },
    { id: "s-p5", providerId: "prov5", providerName: "QuickFix Plumbing", title: "Geyser Installation", category: "Plumbing", price: 600, priceUnit: "unit", description: "Water heater fitting and connection setup", location: "Madurai", image: IMG + "1513694203232-719a280e022f?w=400", rating: 4.7, reviews: 95, availability: "Available Now", type: "service" },
    { id: "s-p6", providerId: "prov1", providerName: "Kumar Plumbing Works", title: "Kitchen Sink Repair", category: "Plumbing", price: 400, priceUnit: "visit", description: "Fix clogged or damaged kitchen sinks", location: "Madurai", image: IMG + "1556909114-f6e7ad7d3136?w=400", rating: 4.4, reviews: 56, availability: "Available Now", type: "service" },
    { id: "s-p7", providerId: "prov2", providerName: "AquaFix Solutions", title: "Toilet Repair", category: "Plumbing", price: 450, priceUnit: "visit", description: "Flush mechanism, seat, and leak repairs", location: "Madurai", image: IMG + "1564540586988-aa4e53c3d799?w=400", rating: 4.3, reviews: 78, availability: "Available Now", type: "service" },
    { id: "s-p8", providerId: "prov3", providerName: "PipeMasters", title: "Water Purifier Install", category: "Plumbing", price: 700, priceUnit: "unit", description: "RO/UV purifier installation and plumbing", location: "Madurai", image: IMG + "1558618666-fcd25c85b64e?w=400", rating: 4.8, reviews: 112, availability: "Available Now", type: "service" },
    { id: "s-p9", providerId: "prov4", providerName: "Raj Water Works", title: "Overhead Tank Repair", category: "Plumbing", price: 1500, priceUnit: "job", description: "Leak sealing and structural repair of water tanks", location: "Madurai", image: IMG + "1581094794329-c8112a89af12?w=400", rating: 4.6, reviews: 43, availability: "Available Now", type: "service" },
    { id: "s-p10", providerId: "prov5", providerName: "QuickFix Plumbing", title: "Sump Motor Service", category: "Plumbing", price: 550, priceUnit: "visit", description: "Motor repair, wiring, and pump servicing", location: "Madurai", image: IMG + "1621905252507-b35492cc74b4?w=400", rating: 4.5, reviews: 61, availability: "Available Now", type: "service" },
    { id: "s-p11", providerId: "prov1", providerName: "Kumar Plumbing Works", title: "Pipe Replacement", category: "Plumbing", price: 900, priceUnit: "meter", description: "Old pipe removal and new CPVC/PVC pipe fitting", location: "Madurai", image: IMG + "1504307651254-35680f356dfd?w=400", rating: 4.7, reviews: 88, availability: "Available Now", type: "service" },
    { id: "s-p12", providerId: "prov2", providerName: "AquaFix Solutions", title: "Washing Machine Connect", category: "Plumbing", price: 300, priceUnit: "unit", description: "Inlet and drain pipe setup for washing machines", location: "Madurai", image: IMG + "1626806787461-102c1bfaaea1?w=400", rating: 4.4, reviews: 52, availability: "Available Now", type: "service" },
    { id: "s-p13", providerId: "prov3", providerName: "PipeMasters", title: "Valve Replacement", category: "Plumbing", price: 250, priceUnit: "valve", description: "Gate valve, ball valve, and stop cock replacement", location: "Madurai", image: IMG + "1585704032915-9e4a413f5a45?w=400", rating: 4.3, reviews: 39, availability: "Available Now", type: "service" },
    { id: "s-p14", providerId: "prov4", providerName: "Raj Water Works", title: "Water Pressure Booster", category: "Plumbing", price: 2000, priceUnit: "unit", description: "Booster pump installation for low pressure areas", location: "Madurai", image: IMG + "1513694203232-719a280e022f?w=400", rating: 4.8, reviews: 71, availability: "Available Now", type: "service" },
    { id: "s-p15", providerId: "prov5", providerName: "QuickFix Plumbing", title: "Septic Tank Service", category: "Plumbing", price: 3500, priceUnit: "job", description: "Full septic tank cleaning and maintenance", location: "Madurai", image: IMG + "1504328345606-18bbc8c9d7d1?w=400", rating: 4.6, reviews: 34, availability: "Available Now", type: "service" },

    // ── ELECTRICIAN (15) ──
    { id: "s-e1", providerId: "prov6", providerName: "Spark Electric", title: "Wiring Repair", category: "Electrician", price: 400, priceUnit: "visit", description: "Fix faulty wiring, short circuits, and sparks", location: "Madurai", image: IMG + "1621905251189-08b02d171c20?w=400", rating: 4.7, reviews: 134, availability: "Available Now", type: "service" },
    { id: "s-e2", providerId: "prov7", providerName: "PowerLine Services", title: "Fan Installation", category: "Electrician", price: 300, priceUnit: "fan", description: "Ceiling fan mounting and wiring", location: "Madurai", image: IMG + "1558618666-fcd25c85b64e?w=400", rating: 4.5, reviews: 98, availability: "Available Now", type: "service" },
    { id: "s-e3", providerId: "prov8", providerName: "VoltAge Solutions", title: "Switchboard Repair", category: "Electrician", price: 350, priceUnit: "board", description: "Replace damaged switches, sockets, and boards", location: "Madurai", image: IMG + "1621905252507-b35492cc74b4?w=400", rating: 4.8, reviews: 167, availability: "Available Now", type: "service" },
    { id: "s-e4", providerId: "prov6", providerName: "Spark Electric", title: "MCB/Fuse Box Repair", category: "Electrician", price: 500, priceUnit: "visit", description: "Circuit breaker replacement and fuse box servicing", location: "Madurai", image: IMG + "1581094794329-c8112a89af12?w=400", rating: 4.6, reviews: 76, availability: "Available Now", type: "service" },
    { id: "s-e5", providerId: "prov7", providerName: "PowerLine Services", title: "LED Light Installation", category: "Electrician", price: 200, priceUnit: "light", description: "Panel lights, strip lights, and downlight fitting", location: "Madurai", image: IMG + "1513694203232-719a280e022f?w=400", rating: 4.4, reviews: 112, availability: "Available Now", type: "service" },
    { id: "s-e6", providerId: "prov8", providerName: "VoltAge Solutions", title: "Inverter Setup", category: "Electrician", price: 1500, priceUnit: "unit", description: "UPS inverter installation with battery wiring", location: "Madurai", image: IMG + "1504307651254-35680f356dfd?w=400", rating: 4.9, reviews: 89, availability: "Available Now", type: "service" },
    { id: "s-e7", providerId: "prov6", providerName: "Spark Electric", title: "AC Wiring", category: "Electrician", price: 800, priceUnit: "unit", description: "Dedicated AC point and stabilizer wiring", location: "Madurai", image: IMG + "1556909114-f6e7ad7d3136?w=400", rating: 4.7, reviews: 54, availability: "Available Now", type: "service" },
    { id: "s-e8", providerId: "prov7", providerName: "PowerLine Services", title: "Doorbell Install", category: "Electrician", price: 250, priceUnit: "unit", description: "Wired and wireless doorbell installation", location: "Madurai", image: IMG + "1558618666-fcd25c85b64e?w=400", rating: 4.3, reviews: 41, availability: "Available Now", type: "service" },
    { id: "s-e9", providerId: "prov8", providerName: "VoltAge Solutions", title: "Earthing Service", category: "Electrician", price: 2500, priceUnit: "point", description: "Proper earthing setup for home safety", location: "Madurai", image: IMG + "1607472586893-edb57bdc0e39?w=400", rating: 4.8, reviews: 63, availability: "Available Now", type: "service" },
    { id: "s-e10", providerId: "prov6", providerName: "Spark Electric", title: "CCTV Wiring", category: "Electrician", price: 1200, priceUnit: "camera", description: "CCTV camera power and data cable routing", location: "Madurai", image: IMG + "1584622650111-993a426bc7e4?w=400", rating: 4.5, reviews: 87, availability: "Available Now", type: "service" },
    { id: "s-e11", providerId: "prov7", providerName: "PowerLine Services", title: "Generator Connection", category: "Electrician", price: 3000, priceUnit: "job", description: "Generator changeover switch and wiring", location: "Madurai", image: IMG + "1504328345606-18bbc8c9d7d1?w=400", rating: 4.6, reviews: 29, availability: "Available Now", type: "service" },
    { id: "s-e12", providerId: "prov8", providerName: "VoltAge Solutions", title: "Meter Box Repair", category: "Electrician", price: 600, priceUnit: "visit", description: "Energy meter box maintenance and replacement", location: "Madurai", image: IMG + "1621905251189-08b02d171c20?w=400", rating: 4.4, reviews: 45, availability: "Available Now", type: "service" },
    { id: "s-e13", providerId: "prov6", providerName: "Spark Electric", title: "Chandelier Hanging", category: "Electrician", price: 700, priceUnit: "unit", description: "Heavy chandelier mounting with secure anchoring", location: "Madurai", image: IMG + "1513694203232-719a280e022f?w=400", rating: 4.7, reviews: 38, availability: "Available Now", type: "service" },
    { id: "s-e14", providerId: "prov7", providerName: "PowerLine Services", title: "Solar Panel Wiring", category: "Electrician", price: 5000, priceUnit: "setup", description: "Rooftop solar panel electrical connection", location: "Madurai", image: IMG + "1504307651254-35680f356dfd?w=400", rating: 4.9, reviews: 22, availability: "Available Now", type: "service" },
    { id: "s-e15", providerId: "prov8", providerName: "VoltAge Solutions", title: "Home Rewiring", category: "Electrician", price: 8000, priceUnit: "BHK", description: "Complete old wiring replacement for homes", location: "Madurai", image: IMG + "1581094794329-c8112a89af12?w=400", rating: 4.8, reviews: 56, availability: "Available Now", type: "service" },

    // ── CLEANING (15) ──
    { id: "s-c1", providerId: "prov9", providerName: "SparkleClean Pro", title: "Full Home Cleaning", category: "Cleaning", price: 1500, priceUnit: "BHK", description: "Deep cleaning for entire home including kitchen and bath", location: "Madurai", image: IMG + "1581578731548-c64695cc6952?w=400", rating: 4.8, reviews: 245, availability: "Available Now", type: "service" },
    { id: "s-c2", providerId: "prov10", providerName: "CleanSweep", title: "Kitchen Deep Clean", category: "Cleaning", price: 800, priceUnit: "kitchen", description: "Chimney, stove, sink, tiles, and floor scrubbing", location: "Madurai", image: IMG + "1556909114-f6e7ad7d3136?w=400", rating: 4.7, reviews: 187, availability: "Available Now", type: "service" },
    { id: "s-c3", providerId: "prov9", providerName: "SparkleClean Pro", title: "Bathroom Cleaning", category: "Cleaning", price: 500, priceUnit: "bathroom", description: "Tiles, fixtures, glass, and drain deep cleaning", location: "Madurai", image: IMG + "1584622650111-993a426bc7e4?w=400", rating: 4.6, reviews: 143, availability: "Available Now", type: "service" },
    { id: "s-c4", providerId: "prov10", providerName: "CleanSweep", title: "Sofa Shampooing", category: "Cleaning", price: 600, priceUnit: "sofa", description: "Fabric sofa deep cleaning and stain removal", location: "Madurai", image: IMG + "1558618666-fcd25c85b64e?w=400", rating: 4.5, reviews: 98, availability: "Available Now", type: "service" },
    { id: "s-c5", providerId: "prov9", providerName: "SparkleClean Pro", title: "Carpet Cleaning", category: "Cleaning", price: 400, priceUnit: "carpet", description: "Steam cleaning and vacuuming for carpets", location: "Madurai", image: IMG + "1607472586893-edb57bdc0e39?w=400", rating: 4.4, reviews: 76, availability: "Available Now", type: "service" },
    { id: "s-c6", providerId: "prov10", providerName: "CleanSweep", title: "Window Cleaning", category: "Cleaning", price: 300, priceUnit: "window", description: "Glass windows and frames cleaned inside and out", location: "Madurai", image: IMG + "1513694203232-719a280e022f?w=400", rating: 4.3, reviews: 54, availability: "Available Now", type: "service" },
    { id: "s-c7", providerId: "prov9", providerName: "SparkleClean Pro", title: "Mattress Cleaning", category: "Cleaning", price: 500, priceUnit: "mattress", description: "UV sanitization and vacuum cleaning", location: "Madurai", image: IMG + "1504307651254-35680f356dfd?w=400", rating: 4.7, reviews: 89, availability: "Available Now", type: "service" },
    { id: "s-c8", providerId: "prov10", providerName: "CleanSweep", title: "Floor Polishing", category: "Cleaning", price: 1000, priceUnit: "room", description: "Marble, granite, and tile floor polishing", location: "Madurai", image: IMG + "1504328345606-18bbc8c9d7d1?w=400", rating: 4.6, reviews: 67, availability: "Available Now", type: "service" },
    { id: "s-c9", providerId: "prov9", providerName: "SparkleClean Pro", title: "AC Duct Cleaning", category: "Cleaning", price: 700, priceUnit: "unit", description: "Split and window AC filter and duct cleaning", location: "Madurai", image: IMG + "1621905252507-b35492cc74b4?w=400", rating: 4.5, reviews: 45, availability: "Available Now", type: "service" },
    { id: "s-c10", providerId: "prov10", providerName: "CleanSweep", title: "Post-Construction Clean", category: "Cleaning", price: 3000, priceUnit: "BHK", description: "Debris removal, dusting, and full cleaning after renovation", location: "Madurai", image: IMG + "1581094794329-c8112a89af12?w=400", rating: 4.8, reviews: 34, availability: "Available Now", type: "service" },
    { id: "s-c11", providerId: "prov9", providerName: "SparkleClean Pro", title: "Office Cleaning", category: "Cleaning", price: 2000, priceUnit: "office", description: "Workstation, pantry, and restroom cleaning", location: "Madurai", image: IMG + "1581578731548-c64695cc6952?w=400", rating: 4.4, reviews: 56, availability: "Available Now", type: "service" },
    { id: "s-c12", providerId: "prov10", providerName: "CleanSweep", title: "Water Tank Sanitize", category: "Cleaning", price: 600, priceUnit: "tank", description: "Clean and disinfect overhead and sump tanks", location: "Madurai", image: IMG + "1556909114-f6e7ad7d3136?w=400", rating: 4.6, reviews: 41, availability: "Available Now", type: "service" },
    { id: "s-c13", providerId: "prov9", providerName: "SparkleClean Pro", title: "Balcony Cleaning", category: "Cleaning", price: 350, priceUnit: "balcony", description: "Pressure wash and scrub for balcony floors and railings", location: "Madurai", image: IMG + "1584622650111-993a426bc7e4?w=400", rating: 4.3, reviews: 28, availability: "Available Now", type: "service" },
    { id: "s-c14", providerId: "prov10", providerName: "CleanSweep", title: "Move-In Cleaning", category: "Cleaning", price: 2500, priceUnit: "BHK", description: "Full home sanitization before moving in", location: "Madurai", image: IMG + "1558618666-fcd25c85b64e?w=400", rating: 4.7, reviews: 63, availability: "Available Now", type: "service" },
    { id: "s-c15", providerId: "prov9", providerName: "SparkleClean Pro", title: "Pest Control Combo", category: "Cleaning", price: 1800, priceUnit: "BHK", description: "Cleaning + pest control treatment bundle", location: "Madurai", image: IMG + "1607472586893-edb57bdc0e39?w=400", rating: 4.9, reviews: 112, availability: "Available Now", type: "service" },

    // ── PAINTING (15) ──
    { id: "s-pt1", providerId: "prov11", providerName: "ColorCraft Painters", title: "Interior Wall Paint", category: "Painting", price: 18, priceUnit: "sqft", description: "Premium emulsion paint for interior walls", location: "Madurai", image: IMG + "1562259949-e8e7689d7828?w=400", rating: 4.8, reviews: 156, availability: "Available Now", type: "service" },
    { id: "s-pt2", providerId: "prov12", providerName: "BrushStroke Studio", title: "Exterior Paint", category: "Painting", price: 22, priceUnit: "sqft", description: "Weather-proof exterior wall painting", location: "Madurai", image: IMG + "1558618666-fcd25c85b64e?w=400", rating: 4.7, reviews: 98, availability: "Available Now", type: "service" },
    { id: "s-pt3", providerId: "prov11", providerName: "ColorCraft Painters", title: "Texture Finish", category: "Painting", price: 35, priceUnit: "sqft", description: "Decorative texture paint for accent walls", location: "Madurai", image: IMG + "1584622650111-993a426bc7e4?w=400", rating: 4.9, reviews: 87, availability: "Available Now", type: "service" },
    { id: "s-pt4", providerId: "prov12", providerName: "BrushStroke Studio", title: "Wood Polish", category: "Painting", price: 800, priceUnit: "door", description: "Door and furniture wood polishing and varnish", location: "Madurai", image: IMG + "1504307651254-35680f356dfd?w=400", rating: 4.5, reviews: 65, availability: "Available Now", type: "service" },
    { id: "s-pt5", providerId: "prov11", providerName: "ColorCraft Painters", title: "Waterproofing", category: "Painting", price: 45, priceUnit: "sqft", description: "Terrace and wall waterproofing coating", location: "Madurai", image: IMG + "1513694203232-719a280e022f?w=400", rating: 4.6, reviews: 78, availability: "Available Now", type: "service" },
    { id: "s-pt6", providerId: "prov12", providerName: "BrushStroke Studio", title: "Stencil Art", category: "Painting", price: 50, priceUnit: "sqft", description: "Custom stencil designs for feature walls", location: "Madurai", image: IMG + "1562259949-e8e7689d7828?w=400", rating: 4.8, reviews: 43, availability: "Available Now", type: "service" },
    { id: "s-pt7", providerId: "prov11", providerName: "ColorCraft Painters", title: "Ceiling Paint", category: "Painting", price: 15, priceUnit: "sqft", description: "Smooth ceiling painting with primer coat", location: "Madurai", image: IMG + "1556909114-f6e7ad7d3136?w=400", rating: 4.4, reviews: 56, availability: "Available Now", type: "service" },
    { id: "s-pt8", providerId: "prov12", providerName: "BrushStroke Studio", title: "Metal Gate Paint", category: "Painting", price: 600, priceUnit: "gate", description: "Rust removal, primer, and enamel paint for metal gates", location: "Madurai", image: IMG + "1581094794329-c8112a89af12?w=400", rating: 4.3, reviews: 34, availability: "Available Now", type: "service" },
    { id: "s-pt9", providerId: "prov11", providerName: "ColorCraft Painters", title: "Wallpaper Install", category: "Painting", price: 40, priceUnit: "sqft", description: "Premium wallpaper selection and installation", location: "Madurai", image: IMG + "1504328345606-18bbc8c9d7d1?w=400", rating: 4.7, reviews: 67, availability: "Available Now", type: "service" },
    { id: "s-pt10", providerId: "prov12", providerName: "BrushStroke Studio", title: "Epoxy Flooring", category: "Painting", price: 60, priceUnit: "sqft", description: "Durable epoxy coating for garage and industrial floors", location: "Madurai", image: IMG + "1607472586893-edb57bdc0e39?w=400", rating: 4.6, reviews: 29, availability: "Available Now", type: "service" },
    { id: "s-pt11", providerId: "prov11", providerName: "ColorCraft Painters", title: "Kids Room Theme", category: "Painting", price: 5000, priceUnit: "wall", description: "Cartoon and theme wall art for kids rooms", location: "Madurai", image: IMG + "1621905252507-b35492cc74b4?w=400", rating: 4.9, reviews: 45, availability: "Available Now", type: "service" },
    { id: "s-pt12", providerId: "prov12", providerName: "BrushStroke Studio", title: "Anti-Fungal Paint", category: "Painting", price: 25, priceUnit: "sqft", description: "Moisture-resistant anti-fungal wall treatment", location: "Madurai", image: IMG + "1581578731548-c64695cc6952?w=400", rating: 4.5, reviews: 38, availability: "Available Now", type: "service" },
    { id: "s-pt13", providerId: "prov11", providerName: "ColorCraft Painters", title: "Primer Coating", category: "Painting", price: 10, priceUnit: "sqft", description: "Base primer coat for new and repainted walls", location: "Madurai", image: IMG + "1562259949-e8e7689d7828?w=400", rating: 4.4, reviews: 52, availability: "Available Now", type: "service" },
    { id: "s-pt14", providerId: "prov12", providerName: "BrushStroke Studio", title: "Colour Consultation", category: "Painting", price: 500, priceUnit: "session", description: "Expert colour palette advice for your home", location: "Madurai", image: IMG + "1558618666-fcd25c85b64e?w=400", rating: 4.7, reviews: 21, availability: "Available Now", type: "service" },
    { id: "s-pt15", providerId: "prov11", providerName: "ColorCraft Painters", title: "Touch-Up Paint", category: "Painting", price: 200, priceUnit: "wall", description: "Small area patch and touch-up painting", location: "Madurai", image: IMG + "1584622650111-993a426bc7e4?w=400", rating: 4.3, reviews: 67, availability: "Available Now", type: "service" },

    // ── REPAIRS (15) ──
    { id: "s-r1", providerId: "prov13", providerName: "FixIt Masters", title: "Door Hinge Repair", category: "Repairs", price: 250, priceUnit: "door", description: "Loose hinge tightening and replacement", location: "Madurai", image: IMG + "1581094794329-c8112a89af12?w=400", rating: 4.6, reviews: 89, availability: "Available Now", type: "service" },
    { id: "s-r2", providerId: "prov14", providerName: "HandyPro", title: "Window Fix", category: "Repairs", price: 400, priceUnit: "window", description: "Broken glass, handle, and lock repair", location: "Madurai", image: IMG + "1504307651254-35680f356dfd?w=400", rating: 4.5, reviews: 67, availability: "Available Now", type: "service" },
    { id: "s-r3", providerId: "prov13", providerName: "FixIt Masters", title: "Furniture Assembly", category: "Repairs", price: 500, priceUnit: "item", description: "Flat-pack furniture assembly and setup", location: "Madurai", image: IMG + "1556909114-f6e7ad7d3136?w=400", rating: 4.7, reviews: 123, availability: "Available Now", type: "service" },
    { id: "s-r4", providerId: "prov14", providerName: "HandyPro", title: "Wall Mounting", category: "Repairs", price: 300, priceUnit: "item", description: "TV, shelf, and frame wall mounting", location: "Madurai", image: IMG + "1513694203232-719a280e022f?w=400", rating: 4.4, reviews: 98, availability: "Available Now", type: "service" },
    { id: "s-r5", providerId: "prov13", providerName: "FixIt Masters", title: "Lock & Key Repair", category: "Repairs", price: 350, priceUnit: "lock", description: "Door lock repair, replacement, and key cutting", location: "Madurai", image: IMG + "1584622650111-993a426bc7e4?w=400", rating: 4.8, reviews: 145, availability: "Available Now", type: "service" },
    { id: "s-r6", providerId: "prov14", providerName: "HandyPro", title: "Curtain Rod Install", category: "Repairs", price: 250, priceUnit: "rod", description: "Curtain rod and bracket fitting", location: "Madurai", image: IMG + "1558618666-fcd25c85b64e?w=400", rating: 4.3, reviews: 45, availability: "Available Now", type: "service" },
    { id: "s-r7", providerId: "prov13", providerName: "FixIt Masters", title: "Tile Replacement", category: "Repairs", price: 150, priceUnit: "tile", description: "Cracked or broken tile removal and replacement", location: "Madurai", image: IMG + "1607472586893-edb57bdc0e39?w=400", rating: 4.6, reviews: 56, availability: "Available Now", type: "service" },
    { id: "s-r8", providerId: "prov14", providerName: "HandyPro", title: "Drawer Repair", category: "Repairs", price: 300, priceUnit: "drawer", description: "Drawer slide, handle, and panel repair", location: "Madurai", image: IMG + "1504328345606-18bbc8c9d7d1?w=400", rating: 4.5, reviews: 34, availability: "Available Now", type: "service" },
    { id: "s-r9", providerId: "prov13", providerName: "FixIt Masters", title: "Roof Leak Patch", category: "Repairs", price: 1200, priceUnit: "job", description: "Minor roof leak patching and sealing", location: "Madurai", image: IMG + "1621905252507-b35492cc74b4?w=400", rating: 4.7, reviews: 28, availability: "Available Now", type: "service" },
    { id: "s-r10", providerId: "prov14", providerName: "HandyPro", title: "Gate Welding", category: "Repairs", price: 800, priceUnit: "job", description: "Iron gate and grill welding and repair", location: "Madurai", image: IMG + "1581578731548-c64695cc6952?w=400", rating: 4.4, reviews: 41, availability: "Available Now", type: "service" },
    { id: "s-r11", providerId: "prov13", providerName: "FixIt Masters", title: "Mosquito Net Fix", category: "Repairs", price: 200, priceUnit: "window", description: "Mosquito mesh repair and new installation", location: "Madurai", image: IMG + "1562259949-e8e7689d7828?w=400", rating: 4.3, reviews: 56, availability: "Available Now", type: "service" },
    { id: "s-r12", providerId: "prov14", providerName: "HandyPro", title: "Closet Repair", category: "Repairs", price: 600, priceUnit: "closet", description: "Wardrobe door, shelf, and hinge repair", location: "Madurai", image: IMG + "1584622650111-993a426bc7e4?w=400", rating: 4.6, reviews: 39, availability: "Available Now", type: "service" },
    { id: "s-r13", providerId: "prov13", providerName: "FixIt Masters", title: "Ceiling Crack Fix", category: "Repairs", price: 500, priceUnit: "area", description: "Ceiling crack filling and plastering", location: "Madurai", image: IMG + "1556909114-f6e7ad7d3136?w=400", rating: 4.5, reviews: 23, availability: "Available Now", type: "service" },
    { id: "s-r14", providerId: "prov14", providerName: "HandyPro", title: "Appliance Install", category: "Repairs", price: 400, priceUnit: "item", description: "Geyser, exhaust fan, chimney installation", location: "Madurai", image: IMG + "1513694203232-719a280e022f?w=400", rating: 4.7, reviews: 78, availability: "Available Now", type: "service" },
    { id: "s-r15", providerId: "prov13", providerName: "FixIt Masters", title: "Plaster Patch", category: "Repairs", price: 350, priceUnit: "area", description: "Wall plaster patch and smoothing", location: "Madurai", image: IMG + "1504307651254-35680f356dfd?w=400", rating: 4.4, reviews: 45, availability: "Available Now", type: "service" },

    // ── AC SERVICE (15) ──
    { id: "s-ac1", providerId: "prov15", providerName: "CoolBreeze AC", title: "AC General Service", category: "AC Service", price: 500, priceUnit: "unit", description: "Filter clean, gas check, and general servicing", location: "Madurai", image: IMG + "1504328345606-18bbc8c9d7d1?w=400", rating: 4.8, reviews: 234, availability: "Available Now", type: "service" },
    { id: "s-ac2", providerId: "prov16", providerName: "FrostFix", title: "AC Gas Refill", category: "AC Service", price: 1500, priceUnit: "unit", description: "R22/R410A refrigerant gas top-up", location: "Madurai", image: IMG + "1621905252507-b35492cc74b4?w=400", rating: 4.7, reviews: 156, availability: "Available Now", type: "service" },
    { id: "s-ac3", providerId: "prov15", providerName: "CoolBreeze AC", title: "AC Installation", category: "AC Service", price: 1200, priceUnit: "unit", description: "Split AC indoor and outdoor unit installation", location: "Madurai", image: IMG + "1581094794329-c8112a89af12?w=400", rating: 4.9, reviews: 189, availability: "Available Now", type: "service" },
    { id: "s-ac4", providerId: "prov16", providerName: "FrostFix", title: "AC Uninstallation", category: "AC Service", price: 800, priceUnit: "unit", description: "Safe AC removal for shifting or replacement", location: "Madurai", image: IMG + "1581578731548-c64695cc6952?w=400", rating: 4.5, reviews: 67, availability: "Available Now", type: "service" },
    { id: "s-ac5", providerId: "prov15", providerName: "CoolBreeze AC", title: "AC Deep Clean", category: "AC Service", price: 900, priceUnit: "unit", description: "Jet wash cleaning of filters, coils, and drain", location: "Madurai", image: IMG + "1562259949-e8e7689d7828?w=400", rating: 4.8, reviews: 143, availability: "Available Now", type: "service" },
    { id: "s-ac6", providerId: "prov16", providerName: "FrostFix", title: "AC Compressor Repair", category: "AC Service", price: 3500, priceUnit: "unit", description: "Compressor diagnosis and repair", location: "Madurai", image: IMG + "1556909114-f6e7ad7d3136?w=400", rating: 4.6, reviews: 45, availability: "Available Now", type: "service" },
    { id: "s-ac7", providerId: "prov15", providerName: "CoolBreeze AC", title: "AC PCB Repair", category: "AC Service", price: 2000, priceUnit: "unit", description: "Printed circuit board diagnosis and fix", location: "Madurai", image: IMG + "1584622650111-993a426bc7e4?w=400", rating: 4.4, reviews: 34, availability: "Available Now", type: "service" },
    { id: "s-ac8", providerId: "prov16", providerName: "FrostFix", title: "AC Fan Motor Replace", category: "AC Service", price: 2500, priceUnit: "unit", description: "Indoor/outdoor fan motor replacement", location: "Madurai", image: IMG + "1558618666-fcd25c85b64e?w=400", rating: 4.7, reviews: 28, availability: "Available Now", type: "service" },
    { id: "s-ac9", providerId: "prov15", providerName: "CoolBreeze AC", title: "Window AC Service", category: "AC Service", price: 450, priceUnit: "unit", description: "Complete window AC cleaning and maintenance", location: "Madurai", image: IMG + "1607472586893-edb57bdc0e39?w=400", rating: 4.5, reviews: 89, availability: "Available Now", type: "service" },
    { id: "s-ac10", providerId: "prov16", providerName: "FrostFix", title: "AC Leak Fix", category: "AC Service", price: 1000, priceUnit: "unit", description: "Water and gas leak detection and repair", location: "Madurai", image: IMG + "1513694203232-719a280e022f?w=400", rating: 4.6, reviews: 56, availability: "Available Now", type: "service" },
    { id: "s-ac11", providerId: "prov15", providerName: "CoolBreeze AC", title: "AMC Plan - Annual", category: "AC Service", price: 3000, priceUnit: "year", description: "Annual maintenance contract with 4 services", location: "Madurai", image: IMG + "1504307651254-35680f356dfd?w=400", rating: 4.9, reviews: 112, availability: "Available Now", type: "service" },
    { id: "s-ac12", providerId: "prov16", providerName: "FrostFix", title: "Thermostat Replace", category: "AC Service", price: 800, priceUnit: "unit", description: "Temperature sensor and thermostat replacement", location: "Madurai", image: IMG + "1504328345606-18bbc8c9d7d1?w=400", rating: 4.3, reviews: 23, availability: "Available Now", type: "service" },
    { id: "s-ac13", providerId: "prov15", providerName: "CoolBreeze AC", title: "AC Duct Service", category: "AC Service", price: 1500, priceUnit: "unit", description: "Central AC duct cleaning and sanitization", location: "Madurai", image: IMG + "1621905252507-b35492cc74b4?w=400", rating: 4.7, reviews: 18, availability: "Available Now", type: "service" },
    { id: "s-ac14", providerId: "prov16", providerName: "FrostFix", title: "Stabilizer Install", category: "AC Service", price: 400, priceUnit: "unit", description: "Voltage stabilizer installation for AC protection", location: "Madurai", image: IMG + "1581094794329-c8112a89af12?w=400", rating: 4.4, reviews: 41, availability: "Available Now", type: "service" },
    { id: "s-ac15", providerId: "prov15", providerName: "CoolBreeze AC", title: "AC Shifting", category: "AC Service", price: 2000, priceUnit: "unit", description: "AC relocation with uninstall and reinstall", location: "Madurai", image: IMG + "1581578731548-c64695cc6952?w=400", rating: 4.6, reviews: 34, availability: "Available Now", type: "service" },

    // ── SECURITY (15) ──
    { id: "s-sc1", providerId: "prov17", providerName: "SafeGuard Systems", title: "CCTV Installation", category: "Security", price: 2500, priceUnit: "camera", description: "HD CCTV camera setup with DVR/NVR", location: "Madurai", image: IMG + "1558618666-fcd25c85b64e?w=400", rating: 4.9, reviews: 178, availability: "Available Now", type: "service" },
    { id: "s-sc2", providerId: "prov18", providerName: "SecureHome Pro", title: "Door Lock Smart", category: "Security", price: 3500, priceUnit: "lock", description: "Smart digital door lock installation", location: "Madurai", image: IMG + "1584622650111-993a426bc7e4?w=400", rating: 4.8, reviews: 134, availability: "Available Now", type: "service" },
    { id: "s-sc3", providerId: "prov17", providerName: "SafeGuard Systems", title: "Video Doorbell", category: "Security", price: 2000, priceUnit: "unit", description: "Smart video doorbell with app connectivity", location: "Madurai", image: IMG + "1607472586893-edb57bdc0e39?w=400", rating: 4.7, reviews: 89, availability: "Available Now", type: "service" },
    { id: "s-sc4", providerId: "prov18", providerName: "SecureHome Pro", title: "Alarm System", category: "Security", price: 5000, priceUnit: "setup", description: "Burglar alarm with motion sensors", location: "Madurai", image: IMG + "1513694203232-719a280e022f?w=400", rating: 4.6, reviews: 56, availability: "Available Now", type: "service" },
    { id: "s-sc5", providerId: "prov17", providerName: "SafeGuard Systems", title: "Intercom Install", category: "Security", price: 1800, priceUnit: "unit", description: "Audio/video intercom for apartment gates", location: "Madurai", image: IMG + "1504307651254-35680f356dfd?w=400", rating: 4.5, reviews: 45, availability: "Available Now", type: "service" },
    { id: "s-sc6", providerId: "prov18", providerName: "SecureHome Pro", title: "Fire Alarm Setup", category: "Security", price: 3000, priceUnit: "zone", description: "Smoke detector and fire alarm installation", location: "Madurai", image: IMG + "1556909114-f6e7ad7d3136?w=400", rating: 4.8, reviews: 34, availability: "Available Now", type: "service" },
    { id: "s-sc7", providerId: "prov17", providerName: "SafeGuard Systems", title: "Access Control", category: "Security", price: 8000, priceUnit: "door", description: "Biometric and card-based access control", location: "Madurai", image: IMG + "1581094794329-c8112a89af12?w=400", rating: 4.7, reviews: 23, availability: "Available Now", type: "service" },
    { id: "s-sc8", providerId: "prov18", providerName: "SecureHome Pro", title: "Gate Automation", category: "Security", price: 15000, priceUnit: "gate", description: "Automatic sliding/swing gate motor setup", location: "Madurai", image: IMG + "1504328345606-18bbc8c9d7d1?w=400", rating: 4.9, reviews: 18, availability: "Available Now", type: "service" },
    { id: "s-sc9", providerId: "prov17", providerName: "SafeGuard Systems", title: "CCTV Maintenance", category: "Security", price: 500, priceUnit: "visit", description: "Camera cleaning, angle adjust, and DVR check", location: "Madurai", image: IMG + "1621905252507-b35492cc74b4?w=400", rating: 4.4, reviews: 67, availability: "Available Now", type: "service" },
    { id: "s-sc10", providerId: "prov18", providerName: "SecureHome Pro", title: "Safe Locker Install", category: "Security", price: 1200, priceUnit: "unit", description: "Wall and floor safe locker fitting", location: "Madurai", image: IMG + "1581578731548-c64695cc6952?w=400", rating: 4.6, reviews: 29, availability: "Available Now", type: "service" },
    { id: "s-sc11", providerId: "prov17", providerName: "SafeGuard Systems", title: "Motion Sensor Light", category: "Security", price: 800, priceUnit: "light", description: "Motion-activated security flood lights", location: "Madurai", image: IMG + "1562259949-e8e7689d7828?w=400", rating: 4.5, reviews: 45, availability: "Available Now", type: "service" },
    { id: "s-sc12", providerId: "prov18", providerName: "SecureHome Pro", title: "Panic Button Setup", category: "Security", price: 1500, priceUnit: "unit", description: "Emergency panic button with alert system", location: "Madurai", image: IMG + "1558618666-fcd25c85b64e?w=400", rating: 4.3, reviews: 12, availability: "Available Now", type: "service" },
    { id: "s-sc13", providerId: "prov17", providerName: "SafeGuard Systems", title: "Window Grille", category: "Security", price: 600, priceUnit: "window", description: "Security grille and mesh for windows", location: "Madurai", image: IMG + "1584622650111-993a426bc7e4?w=400", rating: 4.7, reviews: 56, availability: "Available Now", type: "service" },
    { id: "s-sc14", providerId: "prov18", providerName: "SecureHome Pro", title: "Electric Fence", category: "Security", price: 200, priceUnit: "meter", description: "Perimeter electric fence installation", location: "Madurai", image: IMG + "1607472586893-edb57bdc0e39?w=400", rating: 4.6, reviews: 15, availability: "Available Now", type: "service" },
    { id: "s-sc15", providerId: "prov17", providerName: "SafeGuard Systems", title: "Security Audit", category: "Security", price: 2000, priceUnit: "visit", description: "Complete home security assessment and recommendations", location: "Madurai", image: IMG + "1513694203232-719a280e022f?w=400", rating: 4.8, reviews: 22, availability: "Available Now", type: "service" },

    // ── MOVING (15) ──
    { id: "s-m1", providerId: "prov19", providerName: "SwiftMove Packers", title: "Local House Shifting", category: "Moving", price: 3500, priceUnit: "trip", description: "Within-city furniture and goods transport", location: "Madurai", image: IMG + "1504328345606-18bbc8c9d7d1?w=400", rating: 4.7, reviews: 198, availability: "Available Now", type: "service" },
    { id: "s-m2", providerId: "prov20", providerName: "EasyShift Movers", title: "Intercity Move", category: "Moving", price: 12000, priceUnit: "trip", description: "City-to-city packing and moving service", location: "Madurai", image: IMG + "1621905252507-b35492cc74b4?w=400", rating: 4.8, reviews: 145, availability: "Available Now", type: "service" },
    { id: "s-m3", providerId: "prov19", providerName: "SwiftMove Packers", title: "Packing Service", category: "Moving", price: 2000, priceUnit: "BHK", description: "Professional packing with quality materials", location: "Madurai", image: IMG + "1581094794329-c8112a89af12?w=400", rating: 4.6, reviews: 112, availability: "Available Now", type: "service" },
    { id: "s-m4", providerId: "prov20", providerName: "EasyShift Movers", title: "Furniture Disassembly", category: "Moving", price: 500, priceUnit: "item", description: "Bed, wardrobe, and table disassembly for moving", location: "Madurai", image: IMG + "1581578731548-c64695cc6952?w=400", rating: 4.5, reviews: 67, availability: "Available Now", type: "service" },
    { id: "s-m5", providerId: "prov19", providerName: "SwiftMove Packers", title: "Office Relocation", category: "Moving", price: 8000, priceUnit: "office", description: "Complete office furniture and equipment shifting", location: "Madurai", image: IMG + "1556909114-f6e7ad7d3136?w=400", rating: 4.7, reviews: 45, availability: "Available Now", type: "service" },
    { id: "s-m6", providerId: "prov20", providerName: "EasyShift Movers", title: "Vehicle Transport", category: "Moving", price: 5000, priceUnit: "vehicle", description: "Car and bike carrier transport service", location: "Madurai", image: IMG + "1513694203232-719a280e022f?w=400", rating: 4.4, reviews: 34, availability: "Available Now", type: "service" },
    { id: "s-m7", providerId: "prov19", providerName: "SwiftMove Packers", title: "Storage Facility", category: "Moving", price: 1500, priceUnit: "month", description: "Safe warehouse storage for your belongings", location: "Madurai", image: IMG + "1504307651254-35680f356dfd?w=400", rating: 4.6, reviews: 56, availability: "Available Now", type: "service" },
    { id: "s-m8", providerId: "prov20", providerName: "EasyShift Movers", title: "Piano Moving", category: "Moving", price: 3000, priceUnit: "unit", description: "Specialized piano and heavy item moving", location: "Madurai", image: IMG + "1562259949-e8e7689d7828?w=400", rating: 4.8, reviews: 12, availability: "Available Now", type: "service" },
    { id: "s-m9", providerId: "prov19", providerName: "SwiftMove Packers", title: "Unpacking Service", category: "Moving", price: 1500, priceUnit: "BHK", description: "Unpacking and arranging at new location", location: "Madurai", image: IMG + "1584622650111-993a426bc7e4?w=400", rating: 4.5, reviews: 78, availability: "Available Now", type: "service" },
    { id: "s-m10", providerId: "prov20", providerName: "EasyShift Movers", title: "Appliance Moving", category: "Moving", price: 800, priceUnit: "item", description: "Fridge, washing machine, and AC safe moving", location: "Madurai", image: IMG + "1558618666-fcd25c85b64e?w=400", rating: 4.3, reviews: 45, availability: "Available Now", type: "service" },
    { id: "s-m11", providerId: "prov19", providerName: "SwiftMove Packers", title: "Mini Truck Load", category: "Moving", price: 1500, priceUnit: "trip", description: "Small load transport with mini truck", location: "Madurai", image: IMG + "1607472586893-edb57bdc0e39?w=400", rating: 4.6, reviews: 89, availability: "Available Now", type: "service" },
    { id: "s-m12", providerId: "prov20", providerName: "EasyShift Movers", title: "Full Truck Load", category: "Moving", price: 4000, priceUnit: "trip", description: "Large capacity truck for full house shifting", location: "Madurai", image: IMG + "1504328345606-18bbc8c9d7d1?w=400", rating: 4.7, reviews: 98, availability: "Available Now", type: "service" },
    { id: "s-m13", providerId: "prov19", providerName: "SwiftMove Packers", title: "Insurance Cover", category: "Moving", price: 500, priceUnit: "trip", description: "Transit insurance for valuable goods", location: "Madurai", image: IMG + "1621905252507-b35492cc74b4?w=400", rating: 4.4, reviews: 23, availability: "Available Now", type: "service" },
    { id: "s-m14", providerId: "prov20", providerName: "EasyShift Movers", title: "Fragile Items Pack", category: "Moving", price: 300, priceUnit: "item", description: "Special bubble wrap packing for fragile items", location: "Madurai", image: IMG + "1581094794329-c8112a89af12?w=400", rating: 4.8, reviews: 34, availability: "Available Now", type: "service" },
    { id: "s-m15", providerId: "prov19", providerName: "SwiftMove Packers", title: "Loading Help", category: "Moving", price: 600, priceUnit: "hour", description: "Labour for loading and unloading assistance", location: "Madurai", image: IMG + "1581578731548-c64695cc6952?w=400", rating: 4.5, reviews: 56, availability: "Available Now", type: "service" },

    // ── INTERIOR (15) ──
    { id: "s-i1", providerId: "prov21", providerName: "DesignCraft Interiors", title: "Modular Kitchen", category: "Interior", price: 50000, priceUnit: "kitchen", description: "Custom modular kitchen design and installation", location: "Madurai", image: IMG + "1556909114-f6e7ad7d3136?w=400", rating: 4.9, reviews: 167, availability: "Available Now", type: "service" },
    { id: "s-i2", providerId: "prov22", providerName: "HomeStyle Studio", title: "Wardrobe Design", category: "Interior", price: 25000, priceUnit: "unit", description: "Custom sliding or hinged wardrobe", location: "Madurai", image: IMG + "1513694203232-719a280e022f?w=400", rating: 4.8, reviews: 134, availability: "Available Now", type: "service" },
    { id: "s-i3", providerId: "prov21", providerName: "DesignCraft Interiors", title: "False Ceiling", category: "Interior", price: 85, priceUnit: "sqft", description: "Gypsum/POP false ceiling with lighting", location: "Madurai", image: IMG + "1584622650111-993a426bc7e4?w=400", rating: 4.7, reviews: 98, availability: "Available Now", type: "service" },
    { id: "s-i4", providerId: "prov22", providerName: "HomeStyle Studio", title: "TV Unit Design", category: "Interior", price: 15000, priceUnit: "unit", description: "Custom wall-mounted TV unit with storage", location: "Madurai", image: IMG + "1504307651254-35680f356dfd?w=400", rating: 4.6, reviews: 87, availability: "Available Now", type: "service" },
    { id: "s-i5", providerId: "prov21", providerName: "DesignCraft Interiors", title: "Space Planning", category: "Interior", price: 5000, priceUnit: "session", description: "Room layout and furniture placement consultation", location: "Madurai", image: IMG + "1558618666-fcd25c85b64e?w=400", rating: 4.5, reviews: 45, availability: "Available Now", type: "service" },
    { id: "s-i6", providerId: "prov22", providerName: "HomeStyle Studio", title: "Bathroom Vanity", category: "Interior", price: 18000, priceUnit: "unit", description: "Custom bathroom vanity cabinet and mirror", location: "Madurai", image: IMG + "1607472586893-edb57bdc0e39?w=400", rating: 4.7, reviews: 34, availability: "Available Now", type: "service" },
    { id: "s-i7", providerId: "prov21", providerName: "DesignCraft Interiors", title: "Shoe Rack Cabinet", category: "Interior", price: 8000, priceUnit: "unit", description: "Entryway shoe storage cabinet design", location: "Madurai", image: IMG + "1504328345606-18bbc8c9d7d1?w=400", rating: 4.4, reviews: 56, availability: "Available Now", type: "service" },
    { id: "s-i8", providerId: "prov22", providerName: "HomeStyle Studio", title: "Study Table", category: "Interior", price: 12000, priceUnit: "unit", description: "Custom study desk with shelves and drawers", location: "Madurai", image: IMG + "1621905252507-b35492cc74b4?w=400", rating: 4.8, reviews: 78, availability: "Available Now", type: "service" },
    { id: "s-i9", providerId: "prov21", providerName: "DesignCraft Interiors", title: "Pooja Room Design", category: "Interior", price: 20000, priceUnit: "room", description: "Traditional pooja unit with storage and lighting", location: "Madurai", image: IMG + "1581094794329-c8112a89af12?w=400", rating: 4.9, reviews: 89, availability: "Available Now", type: "service" },
    { id: "s-i10", providerId: "prov22", providerName: "HomeStyle Studio", title: "Partition Wall", category: "Interior", price: 10000, priceUnit: "wall", description: "Decorative room divider and partition", location: "Madurai", image: IMG + "1581578731548-c64695cc6952?w=400", rating: 4.5, reviews: 23, availability: "Available Now", type: "service" },
    { id: "s-i11", providerId: "prov21", providerName: "DesignCraft Interiors", title: "Crockery Unit", category: "Interior", price: 22000, priceUnit: "unit", description: "Glass-front crockery display cabinet", location: "Madurai", image: IMG + "1562259949-e8e7689d7828?w=400", rating: 4.6, reviews: 45, availability: "Available Now", type: "service" },
    { id: "s-i12", providerId: "prov22", providerName: "HomeStyle Studio", title: "Bed Design", category: "Interior", price: 30000, priceUnit: "bed", description: "Custom king/queen bed with headboard and storage", location: "Madurai", image: IMG + "1556909114-f6e7ad7d3136?w=400", rating: 4.8, reviews: 67, availability: "Available Now", type: "service" },
    { id: "s-i13", providerId: "prov21", providerName: "DesignCraft Interiors", title: "Flooring Install", category: "Interior", price: 60, priceUnit: "sqft", description: "Wooden, laminate, or vinyl flooring installation", location: "Madurai", image: IMG + "1584622650111-993a426bc7e4?w=400", rating: 4.7, reviews: 34, availability: "Available Now", type: "service" },
    { id: "s-i14", providerId: "prov22", providerName: "HomeStyle Studio", title: "Balcony Makeover", category: "Interior", price: 15000, priceUnit: "balcony", description: "Balcony seating, planters, and lighting design", location: "Madurai", image: IMG + "1513694203232-719a280e022f?w=400", rating: 4.4, reviews: 28, availability: "Available Now", type: "service" },
    { id: "s-i15", providerId: "prov21", providerName: "DesignCraft Interiors", title: "3D Design Render", category: "Interior", price: 3000, priceUnit: "room", description: "Photorealistic 3D rendering of interior design", location: "Madurai", image: IMG + "1504307651254-35680f356dfd?w=400", rating: 4.9, reviews: 56, availability: "Available Now", type: "service" },
];
